openapi: 3.0.0
info:
  version: 0.9.1
  title: API Claims IA
  description: |
    L'API RDV de Claims IA est utilisée dans la cadre du service de prise de rendez-vous de Claims IA.
    Cete API permet aux partenaires, après avoir fixé le rendez-vous, de récupérer les informations détaillées sur le sinistre et la déclaration de l'asuré.

    L'API respecte le standard REST et s'appuie sur les méthodes du protocole HTTP. Les messages échangés sont au format JSON.

    Une clé est nécessaire pour utiliser l'API. Cette clé doit être fournie par la société qui implémente l'API.
  contact:
    name: Edouard Nojaroff
    email: e.nojaroff@claims-ia.fr
servers:
  - url: 'https://base_url/claims/api/v1'
    description: Sample URL
  - url: 'https://api.claims-ia.fr/v1'
    description: Test URL
tags:
  - name: Account
    description: ''
  - name: Appointment
    description: Gestion des rendez-vous.
  - name: Availability
    description: Recherche de créneaux horaires disponibles
  - name: Client
    description: ''
  - name: Custom Field
    description: ''
  - name: Location
    description: Emplacement/adresse d'un site
  - name: Time Zone
    description: ''
  - name: Timeslot
    description: Créneau horaire
paths:
  '/claims/{claimId}':
    parameters:
      - $ref: '#/components/parameters/claimId'
    get:
      summary: LIRE les données d'une déclaration
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
            text/plain:
              schema:
                type: object
                properties: {}
            application/xml:
              schema:
                type: object
                properties: {}
      operationId: get-claim
      description: Déclaration
      parameters: []
      security:
        - header_token: []
  '/claims/{claimId}/files/{fileId}':
    parameters:
      - $ref: '#/components/parameters/claimId'
      - $ref: '#/components/parameters/fileId'
    get:
      summary: RÉCUPÉRER un fichier
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
            application/octet-stream:
              schema:
                type: object
                properties: {}
      operationId: get-claim-file
      description: 'Récupère un fichier '
components:
  securitySchemes:
    header_token:
      type: apiKey
      in: header
      name: ctoken
    http_basic:
      type: http
      scheme: basic
      description: ''
    http_bearer:
      type: http
      scheme: bearer
  responses: {}
  parameters:
    claimId:
      name: claimId
      in: path
      schema:
        type: string
        format: uuid
        example: 123e4567-e89b-12d3-a456-426614174000
      required: true
      description: Identifiant interne d'une déclaration
    fileId:
      name: fileId
      in: path
      schema:
        type: string
      style: matrix
      description: Référence du fichier
      required: true
  examples: {}
  schemas:
    Claim:
      title: Claim
      type: object
      description: Déclaration de sinistre
      x-tags:
        - Claim
      properties:
        date:
          type: string
          format: date-time
          description: Date de déclaration
        company:
          $ref: ../../schemas/Claim/Company.v1.yaml
        contract:
          $ref: ../../schemas/Claim/Contract.v1.yaml
        guarantee:
          $ref: ../../schemas/Claim/WarrantyType.v1.yaml
        customer:
          $ref: ../../schemas/Claim/Customer.v1.yaml
        accident:
          $ref: ../../schemas/Claim/Accident.v1.yaml
        documents:
          type: array
          items:
            $ref: ../../schemas/Common/Attachment.v1.yaml
        valuation:
          $ref: ../../schemas/Claim/Valuation.v1.yaml
        reference:
          type: string
          description: Référence ClaimsIA de la déclaration
        risk:
          $ref: ../../schemas/Claim/Risk.v1.yaml
        missionID:
          type: string
          description: ID coté client
      required:
        - date
        - company
        - guarantee
security:
  - header_token: []
