openapi: 3.0.0
info:
  version: 0.9.1
  title: API Claims IA
  description: |
    L'API RDV de Claims IA est utilisée dans la cadre du service de prise de rendez-vous de Claims IA.
    Cete API permet aux partenaires, après avoir fixé le rendez-vous, de récupérer les informations détaillées sur le sinistre et la déclaration de l'asuré.

    L'API respecte le standard REST et s'appuie sur les méthodes du protocole HTTP. Les messages échangés sont au format JSON.

    Une clé est nécessaire pour utiliser l'API. Cette clé doit être fournie par la société qui implémente l'API.
  contact:
    name: Edouard Nojaroff
    email: e.nojaroff@claims-ia.fr
servers:
  - url: 'https://base_url/claims/api/v1'
    description: Sample URL
  - url: 'https://api.claims-ia.fr/v1'
    description: Test URL
tags:
  - name: Account
    description: ''
  - name: Appointment
    description: Gestion des rendez-vous.
  - name: Availability
    description: Recherche de créneaux horaires disponibles
  - name: Client
    description: ''
  - name: Custom Field
    description: ''
  - name: Location
    description: Emplacement/adresse d'un site
  - name: Time Zone
    description: ''
  - name: Timeslot
    description: Créneau horaire
paths:
  '/claims/{cid}':
    parameters:
      - schema:
          type: string
          example: cd83ea81-5ca1-4a1b-a155-2e4d99f04a6a
          format: uuid
        name: cid
        in: path
        required: true
        description: Identifiant de la déclaration
    get:
      summary: LIRE les données d'une déclaration
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Claim.v1.yaml
      operationId: get-claim
      description: km
      parameters: []
  '/claims/{claimId}/files/{fileId}':
    parameters:
      - schema:
          type: string
        name: claimId
        in: path
        required: true
      - schema:
          type: string
        name: fileId
        in: path
        required: true
    get:
      summary: LIRE un fichier
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: object
                properties: {}
      operationId: get-claim-file
      description: Récupère un fichier de la déclaration
components:
  securitySchemes:
    header_token:
      type: apiKey
      in: header
      name: ctoken
    http_basic:
      type: http
      scheme: basic
      description: ''
    http_bearer:
      type: http
      scheme: bearer
  responses: {}
  parameters: {}
  examples: {}
security:
  - header_token: []
