type: string
title: Type de plafond d'indemnisation
enum:
  - PlafondImmobilier
  - PlafondMobilier
  - PlafondBijoux
  - CapitalDeBase
  - PlafondDesObjetsDeValeur
  - PlafondInstallationsExterieures
  - PlafondMobilierDeclare
  - PlafondMobilierOrdinaire
  - PlafondVeranda
  - PlafondContenuDependances
  - PlafondPiscine
  - PlafondDeRevente
  - PlafondRechercheDeFuite
  - PlafondAutresBiensExterieurs
  - PlafondSurconsommationDEau
  - PlafondBrisAccidentelDeBiensMultimedia
  - PlafondVolALExterieur
  - PlafondAutre
  - PlafondDependances
  - PlafondMobilierProfessionnel
  - PlafondImmobilierDependanceMemeAdresse
  - PlafondImmobilierDependanceAutreAdresse
  - PlafondCanalisationsExterieures
  - PlafondGtieVillegiature
  - BienInvites
  - BiensDepositaire
  - EauRuissellementRefoulementEgouts
  - FraisRéparationAppareilEffetDEauConduiteGel
  - BiensEntreposesImmeubleConstruction
  - PlafondMobilierDependanceAutreAdresse
description: ''
x-tags:
  - Claim
